sources:
  - name: raw
    schema: gz_raw_data
    tables:
    
      - name: adwords
        identifier: raw_gz_adwords
        description: raw adwords table 
      
      - name: bing 
        identifier: raw_gz_bing
        description: raw bing table 

      - name: criteo 
        identifier: raw_gz_criteo
        description: raw criteo table 

      - name: facebook
        identifier: raw_gz_facebook
        description: raw facebook table 

      - name: sales
        identifier: raw_gz_sales
        description: raw sales table 

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: unique product identifier
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price of the product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data of Greenweez
        columns:
          - name: orders_id
            description: order identifier