sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: 

      - name: product
        identifier: raw_gz_product
        description: products of Greenweez
        columns:
          - name: products_id
            description: 
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: 

      - name: ship
        identifier: raw_gz_ship
        description: shipping data of Greenweez
        columns:
          - name: orders_id
            description: